### ISSUE TITLE
DLL load failed while importing Delhommeau_f90

### ISSUE THREAD

**Issue by Dadidal** [mancellin/capytaine#131]
Hello! I am marine engineer and new to Capytaine and Python at all. I tried to follow the installation guide and did the following:
1. Installed Visual Studio 2022
2. Installed Intel oneAPI Fortran Compiler (my OS is Windows 10)
3. Using "Intel oneAPI command prompt for Intel 64 for Visual Studio 2022" I installed Capytaine:
- pip install numpy
- pip install matplotlib
- pip install capytaine

Im command promt I obtained the message that Capytaine is installed

4. Installed VS Code

Everything looked fine and tried to start following Example from your website in VS Code:

```
import numpy as np
import xarray as xr
import capytaine as cpt

# Initialize floating body by generating a geometric mesh
cylinder = cpt.HorizontalCylinder(
    length=10.0, radius=1.0,  # Dimensions
    center=(0, 0, -2),        # Position
    nr=5, nx=40, ntheta=20,   # Fineness of the mesh
)

# Automatically add the six degrees of freedom of a rigid body
cylinder.add_all_rigid_body_dofs()

# Define the range of frequencies as a Numpy array
omega_range = np.linspace(0.1, 6.0, 20)

# Set up the problems: we will solve a radiation problem for each
# degree of freedom of the body and for each frequency in the
# frequency range.
problems = [
    cpt.RadiationProblem(body=cylinder, radiating_dof=dof, omega=omega)
    for dof in cylinder.dofs
    for omega in omega_range
]
# Water density, gravity and water depth have not been specified.
# Default values are used.

# Solve all radiation problems
solver = cpt.BEMSolver()
results = [solver.solve(pb) for pb in sorted(problems)]
# The 'sorted' function ensures that the problems are sequentially
# treated in an optimal order.

# Gather the computed added mass into a labelled array.
data = cpt.assemble_dataset(results)

# Plot the added mass of each dofs as a function of the frequency
import matplotlib.pyplot as plt
plt.figure()
for dof in cylinder.dofs:
    plt.plot(
        omega_range,
        data['added_mass'].sel(radiating_dof=dof, influenced_dof=dof),
        label=dof,
        marker='o',
    )
plt.xlabel('omega')
plt.ylabel('added mass')
plt.legend()
plt.tight_layout()
plt.show()
```
After that I obtained the following error:

```
Traceback (most recent call last):
  File "c:\Projects\PhD study\AE_study\Test.py", line 3, in <module>
    import capytaine as cpt
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\capytaine\__init__.py", line 21, in <module>  
    from capytaine.bem.solver import Nemoh, BEMSolver
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\capytaine\bem\solver.py", line 23, in <module>
    from capytaine.green_functions.delhommeau import Delhommeau
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\capytaine\green_functions\delhommeau.py", line 15, in <module>
    import capytaine.green_functions.Delhommeau_f90 as Delhommeau_f90
ImportError: DLL load failed while importing Delhommeau_f90: The specified module could not be found.
```
Could you please help to solve this?

Thank you

**Comment by mancellin** [comment]
Seems to be the same as #111. The cause (incompatibility between some DLLs) was unclear, but a solution was to work in a new clean conda environment.

Your case might be slightly different since you are compiling the code yourself. I have few experience of compiling Capytaine on Windows and none with Intel oneAPI Fortran Compiler (=`ifort`?)...

**Comment by Dadidal** [comment]
Thank you, the problem was solved using conda installation and new environment!
