### ISSUE TITLE
ModuleNotFoundError: No module named 'vtkIOParallelPython'

### ISSUE THREAD

**Issue by maoyanjun** [mancellin/capytaine#16]
I install capytaine by conda as blow:
`` conda install -c conda-forge capytaine``

Python version: ``Python 3.6.7 | packaged by conda-forge |``
When I run the example case ``animate_free_surface.py``, I got below error. Can anyone help me?

```python
Traceback (most recent call last):
  File "/home/maxz/anaconda3/lib/python3.6/site-packages/vtk/vtkIOParallel.py", line 5, in <module>
    from .vtkIOParallelPython import *
ImportError: libjsoncpp.so.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "animate_free_surface.py", line 6, in <module>
    from capytaine.ui.vtk.animation import Animation
  File "/home/maxz/anaconda3/lib/python3.6/site-packages/capytaine/ui/vtk/__init__.py", line 4, in <module>
    from capytaine.ui.vtk.mesh_viewer import MeshViewer
  File "/home/maxz/anaconda3/lib/python3.6/site-packages/capytaine/ui/vtk/mesh_viewer.py", line 13, in <module>
    import vtk
  File "/home/maxz/anaconda3/lib/python3.6/site-packages/vtk/__init__.py", line 80, in <module>
    from .vtkIOParallel import *
  File "/home/maxz/anaconda3/lib/python3.6/site-packages/vtk/vtkIOParallel.py", line 9, in <module>
    from vtkIOParallelPython import *
ModuleNotFoundError: No module named 'vtkIOParallelPython'
```

**Comment by mancellin** [comment]
Hi @maoyanjun
Something seems to be wrong with the VTK package used by Capytaine for 3D displays.
Try maybe the suggestions from this thread: https://github.com/conda-forge/vtk-feedstock/issues/46

**Comment by mancellin** [comment]
@maoyanjun, did you manage to solve your problem?
There isn't much I can do on my side since it is mostly a problem in the distribution of VTK.

**Comment by yang-jiaye** [comment]
I also met same problem
