### ISSUE TITLE
Save hydrodata in netCDF format - dtype object

### ISSUE THREAD

**Issue by sdillenburg** [mancellin/capytaine#2]
Hi Matthieu, all,

When using the test_matrix as described [here](https://ancell.in/capytaine/latest/user_manual/problem_setup.html), saving the hydrodata in netCDF format does not work:

```
<xarray.Dataset>
Dimensions:              (angle: 2, influenced_dof: 6, omega: 5, radiating_dof: 6)
Coordinates:
  * omega                (omega) float64 0.1 0.55 1.0 1.45 1.9
  * radiating_dof        (radiating_dof) object 'Heave' 'Pitch' ... 'Sway' 'Yaw'
  * influenced_dof       (influenced_dof) object 'Heave' 'Pitch' ... 'Yaw'
  * angle                (angle) float64 0.0 3.142
Data variables:
    added_mass           (omega, radiating_dof, influenced_dof) float64 6.104e+06 ... 2.773e+08
    radiation_damping    (omega, radiating_dof, influenced_dof) float64 1.676e+05 ... 8.082e+08
    Froude_Krylov_force  (omega, angle, influenced_dof) complex128 (5586514.371997109+712973.1754521467j) ... (3074.6924403151497+1928.170682615193j)
    convention           (omega, angle, influenced_dof) object 'Nemoh' ... 'Nemoh'
    diffraction_force    (omega, angle, influenced_dof) complex128 (-57663.37262132119-25599.65326598713j) ... (-3518.1643708875167-3340.690725433078j)
Attributes:
    g:            9.81
    rho:          1000
    body_name:    osv.gdf
    water_depth:  50.0
```

I do get the following error message:

```
Traceback (most recent call last):
  File "./test.py", line 65, in <module>
    separate_complex_values(dataset).to_netcdf('osv.nc')
  File "/home/simon/miniconda3/lib/python3.6/site-packages/xarray/core/dataset.py", line 1222, in to_netcdf
    compute=compute)
  File "/home/simon/miniconda3/lib/python3.6/site-packages/xarray/backends/api.py", line 718, in to_netcdf
    unlimited_dims=unlimited_dims)
  File "/home/simon/miniconda3/lib/python3.6/site-packages/xarray/backends/api.py", line 761, in dump_to_store
    unlimited_dims=unlimited_dims)
  File "/home/simon/miniconda3/lib/python3.6/site-packages/xarray/backends/common.py", line 266, in store
    unlimited_dims=unlimited_dims)
  File "/home/simon/miniconda3/lib/python3.6/site-packages/xarray/backends/common.py", line 304, in set_variables
    name, v, check, unlimited_dims=unlimited_dims)
  File "/home/simon/miniconda3/lib/python3.6/site-packages/xarray/backends/netCDF4_.py", line 434, in prepare_variable
    raise_on_invalid_encoding=check_encoding)
  File "/home/simon/miniconda3/lib/python3.6/site-packages/xarray/backends/netCDF4_.py", line 107, in _get_datatype
    datatype = _nc4_dtype(var)
  File "/home/simon/miniconda3/lib/python3.6/site-packages/xarray/backends/netCDF4_.py", line 130, in _nc4_dtype
    .format(var.dtype))
ValueError: unsupported dtype for netCDF4 variable: object
```

The convection variable seems to be the issue.

Here's the full Python code:
```
#!/usr/bin/env python

import logging

import numpy as np
import xarray as xr
import capytaine as cp

logging.basicConfig(level=logging.INFO,
                    format="%(levelname)s:\t%(message)s")

# Profile of the axisymmetric body
def shape(z):
    return 0.1*(-(z+1)**2 + 16)

buoy = cp.FloatingBody(
    cp.AxialSymmetry.from_profile(shape, z_range=np.linspace(-5, 0, 30), nphi=40)
)

buoy.add_translation_dof(name="Heave")

test_matrix = xr.Dataset(coords={
    'omega': np.linspace(0.1, 4, 40),
    'angle': [0, np.pi/2],
    'radiating_dof': list(buoy.dofs),
    'water_depth': [np.infty],
})

dataset = cp.Nemoh().fill_dataset(test_matrix, [buoy])

print(dataset)

from capytaine.io.xarray import separate_complex_values
separate_complex_values(dataset).to_netcdf('test.nc')
```

**Comment by mancellin** [comment]
Hi @sdillenburg,

I've had this problem before.
It comes from the handling of strings by `xarray`.

The strings used for instance in `radiating_dof` or `convention` can be stored:
* either as NetCDF string objects, which can be written in a NetCDF file;
* or as Python strings stored as generic Python objects, which cannot be written in a NetCDF file.

It would not be a big problem if `xarray` did not sometime change from one to the other without warning.

As a workaround, you can try to force the use of the correct type with the encoding option of `xarray`'s writer:
```
    dataset.to_netcdf("dataset.nc",
                      encoding={'radiating_dof': {'dtype': 'U'},
                                'influenced_dof': {'dtype': 'U'},
                                'convention': {'dtype': 'U'}})
```

**Comment by sdillenburg** [comment]
Thanks. That solves the problem.
